export const MODULE_KEYS = {
  STUDENT_MANAGEMENT: 'STUDENT_MANAGEMENT',
  TEACHER_MANAGEMENT: 'TEACHER_MANAGEMENT',
  ATTENDANCE: 'ATTENDANCE',
  FEES_FINANCE: 'FEES_FINANCE',
  RESULTS_EXAMS: 'RESULTS_EXAMS',
  TIMETABLE: 'TIMETABLE',
  LIBRARY: 'LIBRARY',
  HOSTEL: 'HOSTEL',
  TRANSPORT: 'TRANSPORT',
  HR_PAYROLL: 'HR_PAYROLL',
  PARENT_PORTAL: 'PARENT_PORTAL',
  STUDENT_PORTAL: 'STUDENT_PORTAL',
  LMS: 'LMS',
  ASSIGNMENTS_QUIZ: 'ASSIGNMENTS_QUIZ',
  ADMISSION: 'ADMISSION',
  INVENTORY: 'INVENTORY',
  CERTIFICATES: 'CERTIFICATES',
  ONLINE_CLASSES: 'ONLINE_CLASSES',
  ALUMNI: 'ALUMNI',
  PLACEMENT: 'PLACEMENT',
  RESEARCH: 'RESEARCH',
  SMS_NOTIFICATIONS: 'SMS_NOTIFICATIONS',
  EMAIL_NOTIFICATIONS: 'EMAIL_NOTIFICATIONS',
  ID_CARD_DESIGNER: 'ID_CARD_DESIGNER',
  DOCUMENT_MANAGEMENT: 'DOCUMENT_MANAGEMENT',
};

export const CORE_MODULES = [
  MODULE_KEYS.STUDENT_MANAGEMENT,
  MODULE_KEYS.TEACHER_MANAGEMENT,
  MODULE_KEYS.ATTENDANCE,
  MODULE_KEYS.FEES_FINANCE,
  MODULE_KEYS.RESULTS_EXAMS,
];

export const PORTAL_TYPES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  INSTITUTE_ADMIN: 'INSTITUTE_ADMIN',
  TEACHER: 'TEACHER',
  STUDENT: 'STUDENT',
  PARENT: 'PARENT',
};

export const PORTAL_ROLES = {
  SUPER_ADMIN: ['SUPER_ADMIN'],
  INSTITUTE_ADMIN: ['INSTITUTE_ADMIN', 'ACCOUNTANT', 'HR', 'LIBRARIAN', 'RECEPTIONIST', 'STAFF'],
  TEACHER: ['TEACHER'],
  STUDENT: ['STUDENT'],
  PARENT: ['PARENT'],
};

const ROLE_PORTAL_ROUTE = {
  SUPER_ADMIN: '/sa',
  INSTITUTE_ADMIN: '/admin',
  ACCOUNTANT: '/admin',
  HR: '/admin',
  LIBRARIAN: '/admin',
  RECEPTIONIST: '/admin',
  STAFF: '/admin',
  TEACHER: '/teacher',
  STUDENT: '/student',
  PARENT: '/parent',
};

export function getPortalRouteForRole(role) {
  return ROLE_PORTAL_ROUTE[role] || '/login';
}
