export const PERMISSIONS = {
  SUPER_ADMIN: ['*'],
  INSTITUTE_ADMIN: [
    'MANAGE_STUDENTS', 'MANAGE_TEACHERS', 'MANAGE_COURSES', 'MARK_ATTENDANCE',
    'ENTER_MARKS', 'MANAGE_FEES', 'MANAGE_LIBRARY', 'MANAGE_HR',
    'VIEW_REPORTS_INST', 'MANAGE_TICKETS', 'INSTITUTE_SETTINGS',
  ],
  TEACHER: [
    'VIEW_OWN_STUDENT_DATA', 'MARK_ATTENDANCE', 'ENTER_MARKS',
    'SUBMIT_TICKETS', 'VIEW_OWN_CLASSES',
  ],
  STUDENT: ['VIEW_OWN_STUDENT_DATA', 'VIEW_OWN_FEE', 'SUBMIT_TICKETS'],
  PARENT: ['VIEW_OWN_STUDENT_DATA', 'VIEW_OWN_FEE', 'SUBMIT_TICKETS'],
  ACCOUNTANT: ['MANAGE_FEES', 'VIEW_REPORTS_INST', 'SUBMIT_TICKETS'],
  HR: ['MANAGE_HR', 'SUBMIT_TICKETS'],
  LIBRARIAN: ['MANAGE_LIBRARY', 'SUBMIT_TICKETS'],
  RECEPTIONIST: ['MANAGE_STUDENTS', 'SUBMIT_TICKETS'],
  STAFF: ['SUBMIT_TICKETS'],
};

export function hasPermission(role, permission) {
  const perms = PERMISSIONS[role] || [];
  return perms.includes('*') || perms.includes(permission);
}
