export const PERMISSIONS = {
  SUPER_ADMIN: ['*'],
  INSTITUTE_ADMIN: [
    'MANAGE_STUDENTS', 'MANAGE_TEACHER_PROFILES', 'MANAGE_TEACHER_ASSIGNMENTS',
    'MANAGE_COURSES', 'MARK_ATTENDANCE', 'MANAGE_EXAMS', 'ENTER_MARKS', 'PUBLISH_RESULTS',
    'MANAGE_FEES', 'MANAGE_LIBRARY', 'MANAGE_HR', 'VIEW_REPORTS_INST', 'MANAGE_TIMETABLE',
    'MANAGE_TICKETS', 'INSTITUTE_SETTINGS',
  ],
  PRINCIPAL: [
    'VIEW_OWN_STUDENT_DATA', 'MANAGE_STUDENTS', 'MANAGE_TEACHER_ASSIGNMENTS',
    'MANAGE_COURSES', 'VIEW_REPORTS_INST', 'APPROVE_RESULTS', 'MANAGE_TICKETS',
    'MANAGE_TIMETABLE', 'SUBMIT_TICKETS',
  ],
  EXAM_CONTROLLER: [
    'MANAGE_EXAMS', 'ENTER_MARKS', 'PUBLISH_RESULTS', 'VIEW_REPORTS_INST',
    'MANAGE_TEACHER_ASSIGNMENTS', 'SUBMIT_TICKETS',
  ],
  TEACHER: [
    'VIEW_OWN_STUDENT_DATA', 'MARK_ATTENDANCE', 'ENTER_MARKS',
    'SUBMIT_TICKETS', 'VIEW_OWN_CLASSES',
  ],
  STUDENT: ['VIEW_OWN_STUDENT_DATA', 'VIEW_OWN_FEE', 'SUBMIT_TICKETS'],
  PARENT: ['VIEW_OWN_STUDENT_DATA', 'VIEW_OWN_FEE', 'SUBMIT_TICKETS'],
  ACCOUNTANT: ['MANAGE_FEES', 'VIEW_REPORTS_INST', 'SUBMIT_TICKETS'],
  HR: ['MANAGE_HR', 'MANAGE_TEACHER_PROFILES', 'SUBMIT_TICKETS'],
  LIBRARIAN: ['MANAGE_LIBRARY', 'SUBMIT_TICKETS'],
  RECEPTIONIST: ['MANAGE_STUDENTS', 'MANAGE_TIMETABLE', 'SUBMIT_TICKETS'],
  STAFF: ['SUBMIT_TICKETS'],
};

export function hasPermission(role, permission) {
  const perms = PERMISSIONS[role] || [];
  return perms.includes('*') || perms.includes(permission);
}
