import { Router } from 'express';
import { prisma } from '../../../config/database.js';
import { success, paginated } from '../../../utils/response.js';
import { parsePagination, buildPaginationMeta } from '../../../utils/pagination.js';
import { AppError } from '../../../utils/AppError.js';

const router = Router();

// ─── Announcements (admin-composed broadcasts, visible to students & teachers) ───

router.get('/announcements', async (req, res, next) => {
  try {
    const { page, limit, skip } = parsePagination(req.query);
    const where = { instituteId: req.user.instituteId };
    const [items, total] = await Promise.all([
      prisma.announcement.findMany({ where, skip, take: limit, orderBy: { publishedAt: 'desc' } }),
      prisma.announcement.count({ where }),
    ]);
    return paginated(res, items, buildPaginationMeta(total, page, limit));
  } catch (err) { next(err); }
});

router.post('/announcements', async (req, res, next) => {
  try {
    const { title, content } = req.body;
    if (!title?.trim() || !content?.trim()) throw new AppError('Title and content are required', 400);
    const announcement = await prisma.announcement.create({
      data: { instituteId: req.user.instituteId, title: title.trim(), content: content.trim() },
    });
    return success(res, announcement, 'Announcement published', 201);
  } catch (err) { next(err); }
});

router.delete('/announcements/:id', async (req, res, next) => {
  try {
    const existing = await prisma.announcement.findFirst({ where: { id: req.params.id, instituteId: req.user.instituteId } });
    if (!existing) throw new AppError('Announcement not found', 404);
    await prisma.announcement.delete({ where: { id: existing.id } });
    return success(res, null, 'Announcement removed');
  } catch (err) { next(err); }
});

// ─── System activity feed (auto-generated by the domain event pipeline) ──────────

router.get('/activity', async (req, res, next) => {
  try {
    const { page, limit, skip } = parsePagination(req.query);
    const where = { instituteId: req.user.instituteId };
    const [items, total] = await Promise.all([
      prisma.notification.findMany({ where, skip, take: limit, orderBy: { createdAt: 'desc' } }),
      prisma.notification.count({ where }),
    ]);
    return paginated(res, items, buildPaginationMeta(total, page, limit));
  } catch (err) { next(err); }
});

export default router;
