ALTER TABLE "DegreeBatch" ADD COLUMN IF NOT EXISTS "defaultSemesterFee" DECIMAL(10,2) NOT NULL DEFAULT 0;

ALTER TABLE "DegreeSemester" ALTER COLUMN "semesterFee" DROP NOT NULL;
ALTER TABLE "DegreeSemester" ALTER COLUMN "semesterFee" DROP DEFAULT;

ALTER TABLE "DegreeStudent" ADD COLUMN IF NOT EXISTS "scholarship" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "DegreeStudent" ADD COLUMN IF NOT EXISTS "installmentEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "DegreeStudent" ADD COLUMN IF NOT EXISTS "installmentCount" INTEGER;

ALTER TABLE "DegreeResult" ADD COLUMN IF NOT EXISTS "percentage" DECIMAL(6,2);
ALTER TABLE "DegreeResult" ADD COLUMN IF NOT EXISTS "passPercentage" DECIMAL(5,2) DEFAULT 33;
ALTER TABLE "DegreeResult" ADD COLUMN IF NOT EXISTS "remarks" TEXT;
ALTER TABLE "DegreeResult" ADD COLUMN IF NOT EXISTS "publishedAt" TIMESTAMP(3);
